name: manual workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - staging
          - prod

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Print environment
        run: echo "Running in ${{ github.event.inputs.environment }}"
