name: Cron jobs

on:
  schedule:
    - cron: "30 2 * * 2"   # Every Tuesday at 08:00 AM IST

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Information
        run: echo "This job runs every Tuesday at 8:00 AM IST"
